package interfaces;

import java.sql.*;
import conexion_bd_cu.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.WindowConstants;
/**
 * @author Victor Alejandro Rojas Yovaniniz
 */
public class Administrador extends javax.swing.JFrame {
    
    //Para traer el nombre del usuario declaramos estas variables
    String user, nombre_usuario;
    
    //Variable para enviar datos entre interfaces
    public static int sesion_usuario;
       
    public Administrador() {
        initComponents();
        //Recuperar el nombre usuario desde la interfaz de login para ocuparlo en la interfaz administrador
        user = Login.user;
        
        //Variable con funcion bandera para las jerarquias
        sesion_usuario = 1 ;

        setSize(620,326);//Tamaño de la interfaz
        setResizable(false);//Negar que sea modificable la interfaz
        setTitle("Administrador - " + user); //Nombre de la interfaz y nombre de usuario
        setLocationRelativeTo(null); //Centrar interfaz
        
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE); //El programa dejará de ejecutarse al cerrar
        
        //Conectarse a la base de datos para saber el nombre que se accede al sistema
        try {
            //Crear objeto clase conexión 
            Connection cn = Conexion.conectar();
            //Crear objeto para mandar instrucciones a la base de datos
            PreparedStatement pst = cn.prepareStatement(
                    //Abstraer el nombre de la tabla de usuario donde se igualen los nombres referente al usuario que ingreso
                    "select nombre_usuario from usuarios where username = '" + user + "'");
            
            //Objeto de la clase resulset, para ejecutar la instrucción de la base de datos
            ResultSet rs = pst.executeQuery();
            //Para comprobar coincidencias de las instrucciones enviadas a la base de datos
            if(rs.next()){
                //Lo que se desea obtener bajo la consuta 
                nombre_usuario = rs.getString("nombre_usuario");
                //Imprimir el nombre en a interfaz
                lbl_nombreUsuario.setText("¡ Bienvenido " + nombre_usuario + " !");
            }
            
            
        } catch (Exception e) {
            //Mencion de error 
            System.err.println("Error en conexión desde la interfaz Administrador" + e);
        }
    }
    
    
    //Personalizar icono de Jframe
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nombreUsuario = new javax.swing.JLabel();
        btn_RegistrarUsuario = new javax.swing.JButton();
        btn_GestionarUsuarios = new javax.swing.JButton();
        lbl_gestionarUsuarios = new javax.swing.JLabel();
        lbl_ingresarUsuario = new javax.swing.JLabel();
        lbl_ACLLogo = new javax.swing.JLabel();
        lbl_fondoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nombreUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_RegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestionar.png"))); // NOI18N
        btn_RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, 120));

        btn_GestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        btn_GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_GestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 120));

        lbl_gestionarUsuarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_gestionarUsuarios.setForeground(new java.awt.Color(204, 204, 204));
        lbl_gestionarUsuarios.setText("Gestionar usuarios");
        getContentPane().add(lbl_gestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        lbl_ingresarUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_ingresarUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lbl_ingresarUsuario.setText("Ingresar usuario");
        getContentPane().add(lbl_ingresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        lbl_ACLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aclLogo.png"))); // NOI18N
        getContentPane().add(lbl_ACLLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        lbl_fondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAdmin.png"))); // NOI18N
        getContentPane().add(lbl_fondoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GestionarUsuariosActionPerformed
        RegistrarUsuarios registrarUsuarios = new RegistrarUsuarios();
        registrarUsuarios.setVisible(true);
    }//GEN-LAST:event_btn_GestionarUsuariosActionPerformed

    private void btn_RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarUsuarioActionPerformed
        GestionarUsuarios  gestionarUsuarios = new GestionarUsuarios();
        gestionarUsuarios.setVisible(true);
    }//GEN-LAST:event_btn_RegistrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GestionarUsuarios;
    private javax.swing.JButton btn_RegistrarUsuario;
    private javax.swing.JLabel lbl_ACLLogo;
    private javax.swing.JLabel lbl_fondoAdmin;
    private javax.swing.JLabel lbl_gestionarUsuarios;
    private javax.swing.JLabel lbl_ingresarUsuario;
    private javax.swing.JLabel lbl_nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
