/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import java.sql.*;
import conexion_bd_cu.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Victor Alejandro Rojas Yovaniniz
 */
public class RegistrarUsuarios extends javax.swing.JFrame {
    
    //Recuperar el nombre usuario desde la interfaz de login para ocuparlo en la intefaz administrador
    String user;
  
    public RegistrarUsuarios() {
        initComponents();
        //Recuperar el nombre usuario desde la interfaz de login para ocuparlo en la intefaz administrador
        user = Login.user;
        
        //Variable con de funcion bandera para las jerarquias
        setSize(620,326);//Tamaño de la interfaz
        setResizable(false);//Negar que sea modificable la interfaz
        setTitle("Registrar usuario - Administrador " + user); //Nombre de la interfaz y nombre de usuario
        setLocationRelativeTo(null); //Centrar interfaz
        //Evita que el programa finalice al cerrar registro de usuarios
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); 
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Icono.png"));
        return retValue;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloRegistro = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_Email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        lbl_telefono = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_contrasena = new javax.swing.JLabel();
        txt_contrasena = new javax.swing.JPasswordField();
        chk_MostrarContrasena = new javax.swing.JCheckBox();
        lbl_tipoNivel = new javax.swing.JLabel();
        cmb_niveles = new javax.swing.JComboBox<>();
        btn_registrar = new javax.swing.JButton();
        lbl_oyunde = new javax.swing.JLabel();
        lbl_acl = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tituloRegistro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_tituloRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tituloRegistro.setText("Registro de usuarios");
        getContentPane().add(lbl_tituloRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(204, 204, 204));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(51, 51, 51));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        lbl_Email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Email.setText("Email");
        getContentPane().add(lbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txt_email.setBackground(new java.awt.Color(204, 204, 204));
        txt_email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(51, 51, 51));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, -1));

        txt_telefono.setBackground(new java.awt.Color(204, 204, 204));
        txt_telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(51, 51, 51));
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, -1));

        lbl_telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_telefono.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono.setText("Teléfono");
        getContentPane().add(lbl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txt_username.setBackground(new java.awt.Color(204, 204, 204));
        txt_username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_username.setForeground(new java.awt.Color(51, 51, 51));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 210, -1));

        lbl_username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Cuenta ");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        lbl_contrasena.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contrasena.setText("Contraseña");
        getContentPane().add(lbl_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        txt_contrasena.setBackground(new java.awt.Color(204, 204, 204));
        txt_contrasena.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_contrasena.setForeground(new java.awt.Color(51, 51, 51));
        txt_contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_contrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 210, -1));

        chk_MostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_MostrarContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(chk_MostrarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        lbl_tipoNivel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_tipoNivel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipoNivel.setText("Jerarquía");
        getContentPane().add(lbl_tipoNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        cmb_niveles.setBackground(new java.awt.Color(204, 204, 204));
        cmb_niveles.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmb_niveles.setForeground(new java.awt.Color(51, 51, 51));
        cmb_niveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        cmb_niveles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmb_niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 210, -1));

        btn_registrar.setBackground(new java.awt.Color(204, 204, 204));
        btn_registrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(51, 51, 51));
        btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAgregar.png"))); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        lbl_oyunde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oyu.png"))); // NOI18N
        getContentPane().add(lbl_oyunde, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 50, 80));

        lbl_acl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aclLogo.png"))); // NOI18N
        getContentPane().add(lbl_acl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 30));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoNegro.png"))); // NOI18N
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 619, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void chk_MostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_MostrarContrasenaActionPerformed
        if(chk_MostrarContrasena.isSelected()) {
            txt_contrasena.setEchoChar((char)0);
        }else {
            
            txt_contrasena.setEchoChar('*');
        }
    }//GEN-LAST:event_chk_MostrarContrasenaActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        
        //Inicio de variables permisos, se guardará lo que contenga combo box, 
        //validación se utiliza como variable bandera
        int permisos_cmb, validacion = 0;
        //Valores donde se guardaran los campos que el usuario vaya guardando
        String nombre, email, telefono , username, pass, permisos_string = "";
        
        //Capturando los datos y guardandolos 
        email = txt_email.getText().trim();
        username = txt_username.getText().trim();
        pass = txt_contrasena.getText().trim();
        nombre = txt_nombre.getText().trim();
        telefono = txt_telefono.getText().trim();
        //Se le suma 1 , para el guardado de inicio desde 1 y evitar errores.
        permisos_cmb = cmb_niveles.getSelectedIndex() + 1;
        
        //Estructura condicional para evitar campos vacios
        if(email.equals("")){
            txt_email.setBackground(Color.red);
            //Si la condicion se cumple, incrementar la variable en 1, evitar que el programa no inicie en ejecucion bucle 
            validacion ++;
        }
        
        if(username.equals("")){
            txt_username.setBackground(Color.red);
            //Si la condicion se cumple, incrementar la variable en 1, evitar que el programa no inicie en ejecucion bucle 
            validacion ++;
        }
            
        if(pass.equals("")){
            txt_contrasena.setBackground(Color.red);
            //Si la condicion se cumple, incrementar la variable en 1, evitar que el programa no inicie en ejecucion bucle 
            validacion ++;
        }
        if(nombre.equals("")){
            txt_nombre.setBackground(Color.red);
            //Si la condicion se cumple, incrementar la variable en 1, evitar que el programa no inicie en ejecucion bucle 
            validacion ++;
        }
        if(telefono.equals("")){
            txt_telefono.setBackground(Color.red);
            //Si la condicion se cumple, incrementar la variable en 1, evitar que el programa no inicie en ejecucion bucle 
            validacion ++;
        }
        
        
        //Cambiar los valores enteros por el nombre de la jerarquia
        if(permisos_cmb == 1){
            permisos_string = "Administrador";
        }else if(permisos_cmb == 2) {
            permisos_string = "Usuario";
        }
        
        //Validar con conexión a base de datos que no hayan nombres de cuentas iguales.
        //Realizar consulta
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    //seleccione el nombre de usuario y lo igualo alusername que imprima en pantalla 
                    "select username from usuarios where username = '" + username + "'" );
            //Crear objeto para saber si hay coincidencias en la busqueda solicitada en bd
            ResultSet rs = pst.executeQuery();
            
            //Estructura para coincidencias encontradas o no encontradas
            if(rs.next()){
                txt_username.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de la cuenta no disponibe");
                //Cerrar conexion de base de datos
                cn.close();
            }else{
                //La idea es que si no pasa la condicion tambien cerrarla para que no se siga ejecutando
                cn.close();
                
                //Bandera quiere decir que los campos no esten vacios
                if(validacion == 0){
                    //Inserción de los datos en bd en tabla usuario
                    try {
                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst2 = cn2.prepareStatement(
                                "insert into usuarios values (?,?,?,?,?,?,?,?,?)");
                            pst2.setInt(1, 0);
                            pst2.setString(2, nombre);
                            pst2.setString(3, email);
                            pst2.setString(4,telefono );
                                                        
                            pst2.setString(5,username );
                            pst2.setString(6,pass );
                            //Jerarquia
                            pst2.setString(7,permisos_string );
                            //Al crear un usuario siempre estara activo
                            pst2.setString(8, "Activo");
                            //Guardar quien realizo este guardado
                            pst2.setString(9, user);
                            
                            pst2.executeUpdate();
                            cn2.close();
                            
                            //Metodo creado por mi 
                            Clean();
                            
                            txt_email.setBackground(Color.GREEN);
                            txt_username.setBackground(Color.GREEN);
                            txt_contrasena.setBackground(Color.GREEN);
                            txt_nombre.setBackground(Color.GREEN);
                            txt_telefono.setBackground(Color.GREEN);
                            
                            JOptionPane.showMessageDialog(null, "Registro exitoso.");
                            this.dispose();
                            

                    } catch (SQLException e) {
                        System.err.println("Error al registrar usuario."+ e);
                        JOptionPane.showMessageDialog(null, "Error al registrar, contacte al administrador");

                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos");

                }
             }
            
        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usuario" + e);
            JOptionPane.showMessageDialog(null, "Error al comparar los campos, contactar con administrador");

        }
        

    }//GEN-LAST:event_btn_registrarActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.JCheckBox chk_MostrarContrasena;
    private javax.swing.JComboBox<String> cmb_niveles;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_acl;
    private javax.swing.JLabel lbl_contrasena;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_oyunde;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_tipoNivel;
    private javax.swing.JLabel lbl_tituloRegistro;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables


    public void Clean(){
        txt_contrasena.setText("");
        txt_email.setText("");
        txt_nombre.setText("");
        txt_telefono.setText("");
        txt_username.setText("");
        cmb_niveles.setSelectedIndex(0);

    }
}
